#!/bin/bash
# modules/fs/fs-swap-zram.sh
# Module: ZRAM swap compression
# Enables compressed swap in RAM for better performance

MOD_ID="fs.swap-zram"
MOD_DESC="ZRAM compressed swap"
MOD_STAGE="fs"
MOD_RISK="medium"
MOD_DEFAULT_ENABLED="false"  # Optional, needs evaluation

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    local profile=$(ultra_get_profile)
    local ram_gb=$(ultra_hw_mem_get_total_gb 2>/dev/null || echo "8")
    
    # ZRAM most useful for systems with:
    # - Limited RAM (8GB or less)
    # - Desktop workloads
    # - SSD wear concern
    
    if [[ "$profile" == "desktop" ]] || [[ "$ram_gb" -le 8 ]]; then
        return 0
    fi
    
    # Not recommended for servers with lots of RAM
    if [[ "$ram_gb" -ge 32 ]]; then
        ultra_log_debug "ZRAM not recommended for systems with ${ram_gb}GB RAM"
        return 1
    fi
    
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying ZRAM compressed swap optimization..."
    
    local profile=$(ultra_get_profile)
    local ram_gb=$(ultra_hw_mem_get_total_gb)
    local cores=$(ultra_hw_cpu_get_cores_logical 2>/dev/null || echo "4")
    
    # Check if zram module is available
    if ! modinfo zram &>/dev/null; then
        ultra_log_error "ZRAM kernel module not available"
        ultra_state_finalize_module "$MOD_ID" "failed"
        ultra_log_module_end "$MOD_ID"
        return 1
    fi
    
    # ZRAM configuration
    # Size: typically 50% of RAM for desktop, 25% for server
    local zram_fraction=0.5
    
    case "$profile" in
        desktop)
            zram_fraction=0.5  # 50% of RAM
            ;;
        server)
            zram_fraction=0.25  # 25% of RAM
            ;;
        *)
            zram_fraction=0.33  # 33% of RAM
            ;;
    esac
    
    # Calculate ZRAM size in MB
    local ram_mb=$((ram_gb * 1024))
    local zram_size_mb=$(echo "$ram_mb * $zram_fraction" | bc | cut -d'.' -f1)
    local zram_size="${zram_size_mb}M"
    
    ultra_log_info "ZRAM configuration:"
    ultra_log_info "  System RAM: ${ram_gb}GB"
    ultra_log_info "  ZRAM size: ${zram_size_mb}MB (${zram_fraction} of RAM)"
    ultra_log_info "  Algorithm: lz4 (fast compression)"
    ultra_log_info "  Devices: $cores (one per CPU)"
    
    if ultra_is_dry_run; then
        ultra_log_info "[DRY-RUN] Would configure ZRAM"
        ultra_state_finalize_module "$MOD_ID" "success"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    # Check if zram-tools or zram-generator is available
    if command -v zramctl &>/dev/null; then
        ultra_log_info "Using zramctl for ZRAM setup..."
        
        # Create systemd service for ZRAM
        local service_file="/etc/systemd/system/zram-swap.service"
        
        cat > "$service_file" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
[Unit]
Description=ZRAM Compressed Swap
After=local-fs.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/sh -c 'modprobe zram && echo lz4 > /sys/block/zram0/comp_algorithm && echo $zram_size > /sys/block/zram0/disksize && mkswap /dev/zram0 && swapon -p 100 /dev/zram0'
ExecStop=/bin/sh -c 'swapoff /dev/zram0 && rmmod zram'

[Install]
WantedBy=multi-user.target
EOF
        
        chmod 644 "$service_file"
        systemctl daemon-reload
        
        ultra_state_add_action "$MOD_ID" "systemd" "Created $service_file"
        ultra_log_info "✅ Created: $service_file"
        
        # Enable and start service
        systemctl enable zram-swap.service &>/dev/null
        systemctl start zram-swap.service &>/dev/null
        
        if systemctl is-active zram-swap.service &>/dev/null; then
            ultra_log_info "✅ ZRAM swap activated"
        else
            ultra_log_error "Failed to activate ZRAM swap"
            ultra_state_finalize_module "$MOD_ID" "failed"
            ultra_log_module_end "$MOD_ID"
            return 1
        fi
        
    elif command -v apt-get &>/dev/null; then
        # Try to install zram-tools
        ultra_log_info "Installing zram-tools..."
        apt-get update -qq && apt-get install -y zram-tools &>/dev/null
        
        if [[ $? -eq 0 ]]; then
            # Configure zram-tools
            local config_file="/etc/default/zramswap"
            
            if [[ -f "$config_file" ]]; then
                ultra_backup_file "$config_file" "$MOD_ID"
            fi
            
            cat > "$config_file" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# ZRAM percentage of RAM (0-100)
PERCENT=$((zram_fraction * 100 | bc | cut -d'.' -f1))

# Compression algorithm
ALGO=lz4

# Priority (higher = preferred over disk swap)
PRIORITY=100
EOF
            
            ultra_state_add_action "$MOD_ID" "config" "Created $config_file"
            
            # Restart zram service
            systemctl restart zramswap.service &>/dev/null
            ultra_log_info "✅ ZRAM configured via zram-tools"
        else
            ultra_log_error "Failed to install zram-tools"
            ultra_state_finalize_module "$MOD_ID" "failed"
            ultra_log_module_end "$MOD_ID"
            return 1
        fi
    else
        ultra_log_error "No ZRAM management tool available"
        ultra_state_finalize_module "$MOD_ID" "failed"
        ultra_log_module_end "$MOD_ID"
        return 1
    fi
    
    # Disable traditional swap if ZRAM is working
    ultra_log_info ""
    ultra_log_info "Consider disabling disk swap to fully use ZRAM:"
    ultra_log_info "  swapoff -a"
    ultra_log_info "  # Comment out swap in /etc/fstab"
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    # Stop and disable ZRAM service
    if systemctl is-active zram-swap.service &>/dev/null; then
        systemctl stop zram-swap.service &>/dev/null
        systemctl disable zram-swap.service &>/dev/null
        ultra_log_info "Stopped zram-swap.service"
    fi
    
    if systemctl is-active zramswap.service &>/dev/null; then
        systemctl stop zramswap.service &>/dev/null
        systemctl disable zramswap.service &>/dev/null
        ultra_log_info "Stopped zramswap.service"
    fi
    
    # Remove service file
    local service_file="/etc/systemd/system/zram-swap.service"
    if [[ -f "$service_file" ]]; then
        rm -f "$service_file"
        systemctl daemon-reload
        ultra_log_info "Removed: $service_file"
    fi
    
    # Remove ZRAM devices
    if lsblk | grep -q zram; then
        for zram in /dev/zram*; do
            [[ -b "$zram" ]] && swapoff "$zram" 2>/dev/null
        done
        rmmod zram 2>/dev/null
        ultra_log_info "Removed ZRAM devices"
    fi
}

mod_verify() {
    ultra_log_info "ZRAM Status:"
    
    if lsblk | grep -q zram; then
        ultra_log_info "✅ ZRAM devices active:"
        lsblk | grep zram
        
        # Show compression stats
        if [[ -f /sys/block/zram0/mm_stat ]]; then
            ultra_log_info ""
            ultra_log_info "ZRAM Statistics:"
            local stats=$(cat /sys/block/zram0/mm_stat)
            local orig_size=$(echo "$stats" | awk '{print $1}')
            local comp_size=$(echo "$stats" | awk '{print $2}')
            
            if [[ "$orig_size" -gt 0 ]]; then
                local ratio=$(echo "scale=2; $orig_size / $comp_size" | bc)
                ultra_log_info "  Original size: $((orig_size / 1024 / 1024))MB"
                ultra_log_info "  Compressed size: $((comp_size / 1024 / 1024))MB"
                ultra_log_info "  Compression ratio: ${ratio}x"
            fi
        fi
        
        # Show swap usage
        ultra_log_info ""
        ultra_log_info "Swap status:"
        swapon --show
    else
        ultra_log_warn "❌ No ZRAM devices found"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
