#!/bin/bash
# modules/desktop/desk-laptop-power.sh
# Module: Laptop power optimization
# Integrates TLP and powertop for battery life

MOD_ID="desktop.laptop-power"
MOD_DESC="Laptop power optimization"
MOD_STAGE="desktop"
MOD_RISK="medium"
MOD_DEFAULT_ENABLED="false"

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    # Check if system is a laptop
    local chassis_type=""
    
    if [[ -f /sys/class/dmi/id/chassis_type ]]; then
        chassis_type=$(cat /sys/class/dmi/id/chassis_type)
    fi
    
    # Chassis types: 8=Portable, 9=Laptop, 10=Notebook, 11=Hand Held, 14=Sub Notebook
    if [[ "$chassis_type" != "8" ]] && [[ "$chassis_type" != "9" ]] && [[ "$chassis_type" != "10" ]] && [[ "$chassis_type" != "11" ]] && [[ "$chassis_type" != "14" ]]; then
        # Alternative check: has battery
        if ! ls /sys/class/power_supply/BAT* &>/dev/null; then
            ultra_log_debug "Not a laptop (no battery detected)"
            return 1
        fi
    fi
    
    # Only for desktop profile (or explicitly enabled)
    local profile=$(ultra_get_profile)
    if [[ "$profile" != "desktop" ]]; then
        ultra_log_debug "Not desktop profile"
        return 1
    fi
    
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying laptop power optimization..."
    
    local profile=$(ultra_get_profile)
    
    ultra_log_info "Laptop power management:"
    ultra_log_info "  Tool: TLP (advanced power management)"
    ultra_log_info "  Fallback: powertop tuning"
    
    if ultra_is_dry_run; then
        ultra_log_info "[DRY-RUN] Would install and configure power management"
        ultra_state_finalize_module "$MOD_ID" "success"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    # Check if TLP is available
    local use_tlp=false
    if command -v tlp &>/dev/null; then
        use_tlp=true
        ultra_log_info "✅ TLP is already installed"
    else
        ultra_log_info "Installing TLP..."
        if apt-get install -y tlp tlp-rdw &>/dev/null; then
            use_tlp=true
            ultra_log_info "✅ TLP installed"
        else
            ultra_log_warn "⚠️  Could not install TLP"
        fi
    fi
    
    if $use_tlp; then
        # Configure TLP
        local tlp_config="/etc/tlp.conf"
        
        [[ -f "$tlp_config" ]] && ultra_backup_file "$tlp_config" "$MOD_ID"
        
        # Create TLP configuration
        cat > "$tlp_config" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# TLP power management configuration

# CPU frequency scaling
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_GOVERNOR_ON_BAT=powersave

# CPU energy/performance policy
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power

# CPU boost
CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0

# CPU HWP (Hardware P-states)
CPU_HWP_DYN_BOOST_ON_AC=1
CPU_HWP_DYN_BOOST_ON_BAT=0

# Processor P-states
CPU_MIN_PERF_ON_AC=0
CPU_MAX_PERF_ON_AC=100
CPU_MIN_PERF_ON_BAT=0
CPU_MAX_PERF_ON_BAT=50

# Disk
DISK_IDLE_SECS_ON_AC=0
DISK_IDLE_SECS_ON_BAT=2

# SATA link power management
SATA_LINKPWR_ON_AC="max_performance"
SATA_LINKPWR_ON_BAT="med_power_with_dipm"

# PCI Express ASPM
PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=powersave

# Runtime Power Management
RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto

# WiFi power saving
WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

# USB autosuspend
USB_AUTOSUSPEND=1
USB_EXCLUDE_AUDIO=1
USB_EXCLUDE_BTUSB=0
USB_EXCLUDE_PHONE=0
USB_EXCLUDE_PRINTER=1
USB_EXCLUDE_WWAN=0

# Battery
START_CHARGE_THRESH_BAT0=75
STOP_CHARGE_THRESH_BAT0=80
START_CHARGE_THRESH_BAT1=75
STOP_CHARGE_THRESH_BAT1=80

# Audio
SOUND_POWER_SAVE_ON_AC=0
SOUND_POWER_SAVE_ON_BAT=1
EOF
        
        ultra_log_info "✅ TLP configured: $tlp_config"
        
        # Enable and start TLP
        systemctl enable tlp.service &>/dev/null
        systemctl start tlp.service &>/dev/null
        
        # Mask conflicting services
        systemctl mask systemd-rfkill.service &>/dev/null
        systemctl mask systemd-rfkill.socket &>/dev/null
        
        ultra_log_info "✅ TLP service enabled"
        
        ultra_state_add_action "$MOD_ID" "power" "Configured TLP"
        
    else
        # Fallback: powertop tuning
        ultra_log_info "Using powertop as fallback..."
        
        if ! command -v powertop &>/dev/null; then
            ultra_log_info "Installing powertop..."
            apt-get install -y powertop &>/dev/null
        fi
        
        if command -v powertop &>/dev/null; then
            # Create systemd service for powertop
            local service_file="/etc/systemd/system/powertop-auto-tune.service"
            
            cat > "$service_file" <<EOF
[Unit]
Description=Powertop Auto-Tune
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/powertop --auto-tune
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
            
            systemctl daemon-reload
            systemctl enable powertop-auto-tune.service &>/dev/null
            systemctl start powertop-auto-tune.service &>/dev/null
            
            ultra_log_info "✅ Powertop auto-tune enabled"
            ultra_state_add_action "$MOD_ID" "power" "Configured powertop"
        fi
    fi
    
    ultra_log_info ""
    ultra_log_info "Power management tips:"
    ultra_log_info "  1. Check TLP status:"
    ultra_log_info "     sudo tlp-stat"
    ultra_log_info "  2. Check battery info:"
    ultra_log_info "     sudo tlp-stat -b"
    ultra_log_info "  3. Manual battery threshold (ThinkPad):"
    ultra_log_info "     echo 75 | sudo tee /sys/class/power_supply/BAT0/charge_start_threshold"
    ultra_log_info "     echo 80 | sudo tee /sys/class/power_supply/BAT0/charge_stop_threshold"
    ultra_log_info "  4. Monitor power usage:"
    ultra_log_info "     sudo powertop"
    ultra_log_info "  5. Reduce screen brightness for better battery life"
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    # Stop and disable TLP
    if systemctl is-active tlp.service &>/dev/null; then
        systemctl stop tlp.service &>/dev/null
        systemctl disable tlp.service &>/dev/null
        ultra_log_info "TLP disabled"
    fi
    
    # Unmask systemd-rfkill
    systemctl unmask systemd-rfkill.service &>/dev/null
    systemctl unmask systemd-rfkill.socket &>/dev/null
    
    # Stop powertop auto-tune
    if [[ -f /etc/systemd/system/powertop-auto-tune.service ]]; then
        systemctl stop powertop-auto-tune.service &>/dev/null
        systemctl disable powertop-auto-tune.service &>/dev/null
        rm -f /etc/systemd/system/powertop-auto-tune.service
        systemctl daemon-reload
        ultra_log_info "Powertop auto-tune disabled"
    fi
    
    ultra_log_info "Rollback complete"
    ultra_log_info "Note: TLP package not removed (manual: apt-get remove tlp)"
}

mod_verify() {
    ultra_log_info "Laptop Power Management:"
    
    # Check chassis type
    if [[ -f /sys/class/dmi/id/chassis_type ]]; then
        local chassis=$(cat /sys/class/dmi/id/chassis_type)
        ultra_log_info "Chassis type: $chassis"
    fi
    
    # Check battery
    if ls /sys/class/power_supply/BAT* &>/dev/null; then
        ultra_log_info "✅ Battery detected"
        
        for bat in /sys/class/power_supply/BAT*; do
            local status=$(cat "$bat/status" 2>/dev/null || echo "unknown")
            local capacity=$(cat "$bat/capacity" 2>/dev/null || echo "unknown")
            ultra_log_info "  $(basename "$bat"): $status, $capacity%"
        done
    else
        ultra_log_warn "❌ No battery detected"
    fi
    
    ultra_log_info ""
    ultra_log_info "TLP status:"
    if systemctl is-active tlp.service &>/dev/null; then
        ultra_log_info "✅ TLP is active"
        
        if command -v tlp-stat &>/dev/null; then
            ultra_log_info ""
            tlp-stat -s 2>/dev/null | head -10
        fi
    else
        ultra_log_warn "❌ TLP is not active"
    fi
    
    ultra_log_info ""
    ultra_log_info "Powertop auto-tune:"
    if systemctl is-active powertop-auto-tune.service &>/dev/null; then
        ultra_log_info "✅ Active"
    else
        ultra_log_info "❌ Not active"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
