#!/bin/bash
# modules/desktop/desk-gnome-animation.sh
# Module: GNOME animation optimization
# Reduces or disables animations for faster UI

MOD_ID="desktop.gnome-animation"
MOD_DESC="GNOME animation speed"
MOD_STAGE="desktop"
MOD_RISK="low"
MOD_DEFAULT_ENABLED="false"

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    # Check if GNOME is installed
    if ! command -v gnome-shell &>/dev/null; then
        ultra_log_debug "GNOME not installed"
        return 1
    fi
    
    # Check if gsettings is available
    if ! command -v gsettings &>/dev/null; then
        ultra_log_debug "gsettings not available"
        return 1
    fi
    
    # Only for desktop profile
    local profile=$(ultra_get_profile)
    if [[ "$profile" != "desktop" ]]; then
        ultra_log_debug "Not desktop profile"
        return 1
    fi
    
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying GNOME animation optimization..."
    
    local profile=$(ultra_get_profile)
    
    # Animation speed settings:
    # - enable-animations: true/false (master switch)
    # - animation-speed: 0.5 (faster) to 2.0 (slower), default 1.0
    # - transition-time: in milliseconds
    
    local enable_animations="true"
    local animation_speed="0.5"  # 2x faster
    
    ultra_log_info "GNOME animation configuration:"
    ultra_log_info "  Enable animations: $enable_animations"
    ultra_log_info "  Animation speed: ${animation_speed}x (default: 1.0)"
    ultra_log_info "  Effect: Animations 2x faster for snappier UI"
    
    if ultra_is_dry_run; then
        ultra_log_info "[DRY-RUN] Would configure GNOME animations"
        ultra_state_finalize_module "$MOD_ID" "success"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    # Create script to apply settings
    local script_file="/usr/local/bin/ultra-gnome-animation.sh"
    
    [[ -f "$script_file" ]] && ultra_backup_file "$script_file" "$MOD_ID"
    
    cat > "$script_file" <<EOF
#!/bin/bash
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# Configure GNOME animations for better performance

# Get current user
if [[ -n "\$SUDO_USER" ]]; then
    REAL_USER="\$SUDO_USER"
elif [[ -n "\$USER" ]] && [[ "\$USER" != "root" ]]; then
    REAL_USER="\$USER"
else
    REAL_USER=\$(logname 2>/dev/null || echo "")
fi

if [[ -z "\$REAL_USER" ]] || [[ "\$REAL_USER" == "root" ]]; then
    echo "Cannot determine user for GNOME settings"
    exit 1
fi

# Run gsettings as the actual user
apply_settings() {
    sudo -u "\$REAL_USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/\$(id -u "\$REAL_USER")/bus gsettings set org.gnome.desktop.interface enable-animations $enable_animations
    
    # Note: animation-speed is not a standard gsettings key in all GNOME versions
    # Some GNOME Shell extensions provide this functionality
    
    # Disable some animations for faster response
    sudo -u "\$REAL_USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/\$(id -u "\$REAL_USER")/bus gsettings set org.gnome.shell.extensions.dash-to-dock animation-time 0.1 2>/dev/null || true
    
    # Reduce window animations
    sudo -u "\$REAL_USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/\$(id -u "\$REAL_USER")/bus gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:' 2>/dev/null || true
    
    echo "GNOME animation settings applied for user: \$REAL_USER"
}

apply_settings
EOF
    
    chmod +x "$script_file"
    ultra_log_info "✅ Created: $script_file"
    
    # Apply settings now
    if bash "$script_file" &>/dev/null; then
        ultra_log_info "✅ GNOME settings applied"
    else
        ultra_log_warn "⚠️  Could not apply settings (no active GNOME session?)"
    fi
    
    ultra_state_add_action "$MOD_ID" "desktop" "Configured GNOME animations"
    
    ultra_log_info ""
    ultra_log_info "Additional GNOME optimizations:"
    ultra_log_info "  1. Disable unnecessary extensions:"
    ultra_log_info "     gnome-extensions list"
    ultra_log_info "     gnome-extensions disable <extension-id>"
    ultra_log_info "  2. Reduce visual effects in Tweaks app"
    ultra_log_info "  3. Use lighter themes (Adwaita is optimized)"
    ultra_log_info "  4. Disable file indexing (Tracker) if not needed:"
    ultra_log_info "     systemctl --user mask tracker-store.service"
    ultra_log_info "  5. Install 'Impatience' extension for faster animations"
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    local script_file="/usr/local/bin/ultra-gnome-animation.sh"
    
    # Restore default animation settings
    cat > "$script_file" <<'EOF'
#!/bin/bash
# Restore default GNOME animation settings

if [[ -n "$SUDO_USER" ]]; then
    REAL_USER="$SUDO_USER"
elif [[ -n "$USER" ]] && [[ "$USER" != "root" ]]; then
    REAL_USER="$USER"
else
    REAL_USER=$(logname 2>/dev/null || echo "")
fi

if [[ -z "$REAL_USER" ]] || [[ "$REAL_USER" == "root" ]]; then
    echo "Cannot determine user"
    exit 1
fi

# Reset to defaults
sudo -u "$REAL_USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$REAL_USER")/bus gsettings reset org.gnome.desktop.interface enable-animations
sudo -u "$REAL_USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$REAL_USER")/bus gsettings reset org.gnome.shell.extensions.dash-to-dock animation-time 2>/dev/null || true

echo "GNOME animation settings reset to defaults"
EOF
    
    chmod +x "$script_file"
    bash "$script_file" &>/dev/null
    
    rm -f "$script_file"
    ultra_log_info "Rollback complete"
}

mod_verify() {
    ultra_log_info "GNOME Animation Configuration:"
    
    if [[ -f /usr/local/bin/ultra-gnome-animation.sh ]]; then
        ultra_log_info "✅ Configuration script exists"
    else
        ultra_log_warn "❌ Configuration script not found"
    fi
    
    ultra_log_info ""
    ultra_log_info "Current GNOME settings (if session active):"
    
    # Try to read current user's settings
    if [[ -n "$SUDO_USER" ]]; then
        REAL_USER="$SUDO_USER"
    else
        REAL_USER=$(logname 2>/dev/null || echo "$USER")
    fi
    
    if [[ -n "$REAL_USER" ]] && [[ "$REAL_USER" != "root" ]]; then
        ultra_log_info "User: $REAL_USER"
        
        local enable_anim=$(sudo -u "$REAL_USER" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u "$REAL_USER")/bus gsettings get org.gnome.desktop.interface enable-animations 2>/dev/null || echo "unknown")
        
        ultra_log_info "  enable-animations: $enable_anim"
    else
        ultra_log_warn "Cannot read settings (no user session)"
    fi
    
    ultra_log_info ""
    ultra_log_info "GNOME Shell version:"
    gnome-shell --version 2>/dev/null || echo "Not available"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
