#!/bin/bash
################################################################################
# SYSCTL I/O - Safe sysctl operations with state tracking
################################################################################

ULTRA_SYSCTL_CONF_DIR="/etc/sysctl.d"
ULTRA_SYSCTL_PREFIX="99-ultra-opt"

ultra_sysctl_save_and_set() {
    local key="$1"
    local value="$2"
    local module_id="$3"
    
    # Validate key format
    if [[ ! "$key" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
        ultra_log_error "Invalid sysctl key format: $key"
        return 1
    fi
    
    # Read current value
    local current_value=""
    if [[ -f "/proc/sys/${key//./\/}" ]]; then
        current_value=$(cat "/proc/sys/${key//./\/}" 2>/dev/null || echo "")
    else
        current_value=$(sysctl -n "$key" 2>/dev/null || echo "")
    fi
    
    # Save before state
    ultra_state_save_module_before "$module_id" "sysctl:$key" "$current_value"
    ultra_log_debug "Current value of $key: $current_value"
    
    # Check if already set to target value
    if [[ "$current_value" == "$value" ]]; then
        ultra_log_debug "Sysctl $key already set to $value, skipping"
        ultra_state_save_module_after "$module_id" "sysctl:$key" "$value"
        return 0
    fi
    
    # Dry-run check
    if ultra_is_dry_run; then
        ultra_log_dry_run "sysctl -w $key=$value"
        ultra_state_save_module_after "$module_id" "sysctl:$key" "$value"
        return 0
    fi
    
    # Set runtime value
    if ! sysctl -w "$key=$value" >/dev/null 2>&1; then
        ultra_log_warn "Failed to set runtime value for $key (might be read-only or not available)"
    fi
    
    # Make persistent
    local conf_file="$ULTRA_SYSCTL_CONF_DIR/${ULTRA_SYSCTL_PREFIX}-${module_id//./-}.conf"
    
    # Create or update config file
    if [[ ! -f "$conf_file" ]]; then
        echo "# Generated by Ubuntu Ultra Optimizer" > "$conf_file"
        echo "# Module: $module_id" >> "$conf_file"
        echo "# Generated: $(date -Iseconds)" >> "$conf_file"
        echo "" >> "$conf_file"
    fi
    
    # Remove old entry if exists
    if grep -q "^$key " "$conf_file" 2>/dev/null; then
        sed -i "/^$key /d" "$conf_file"
    fi
    
    # Add new entry
    echo "$key = $value" >> "$conf_file"
    
    # Verify new value
    local new_value=$(sysctl -n "$key" 2>/dev/null || echo "")
    ultra_state_save_module_after "$module_id" "sysctl:$key" "$new_value"
    ultra_state_add_action "$module_id" "sysctl" "Set $key=$value (was: $current_value)"
    
    ultra_log_info "Set $key = $value (was: $current_value)"
}

ultra_sysctl_restore() {
    local key="$1"
    local value="$2"
    local module_id="$3"
    
    ultra_log_info "Restoring $key = $value"
    
    if ultra_is_dry_run; then
        ultra_log_dry_run "sysctl -w $key=$value"
        return 0
    fi
    
    # Set runtime value
    sysctl -w "$key=$value" >/dev/null 2>&1 || true
    
    # Remove from config file
    local conf_file="$ULTRA_SYSCTL_CONF_DIR/${ULTRA_SYSCTL_PREFIX}-${module_id//./-}.conf"
    if [[ -f "$conf_file" ]]; then
        sed -i "/^$key /d" "$conf_file"
        
        # Remove file if empty (only comments left)
        if ! grep -q "^[^#]" "$conf_file" 2>/dev/null; then
            rm -f "$conf_file"
        fi
    fi
}

ultra_sysctl_get_current() {
    local key="$1"
    sysctl -n "$key" 2>/dev/null || echo ""
}

ultra_sysctl_reload_all() {
    if ultra_is_dry_run; then
        ultra_log_dry_run "sysctl --system"
        return 0
    fi
    
    ultra_log_info "Reloading all sysctl settings..."
    sysctl --system >/dev/null 2>&1
}
