#!/bin/bash
# modules/kernel/io/io-nr-requests.sh
# Module: Block device queue depth tuning
# Controls request queue size for better I/O throughput

MOD_ID="kernel.io.nr-requests"
MOD_DESC="Block device queue depth"
MOD_STAGE="kernel-io"
MOD_RISK="low"
MOD_DEFAULT_ENABLED="true"

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    # Check if we have block devices
    local devices=$(lsblk -d -n -o NAME 2>/dev/null | grep -v "loop\|ram")
    if [[ -z "$devices" ]]; then
        ultra_log_debug "No block devices found"
        return 1
    fi
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying block device queue depth optimization..."
    
    local profile=$(ultra_get_profile)
    
    # nr_requests: number of requests in the queue (default: 128-256)
    # Larger queue = more I/O batching, better throughput
    # Smaller queue = lower latency
    
    local nr_requests=256
    
    case "$profile" in
        server)
            # High throughput
            nr_requests=512
            ;;
        db)
            # Balance throughput and latency
            nr_requests=512
            ;;
        lowlatency)
            # Lower latency, smaller queue
            nr_requests=128
            ;;
        desktop)
            # Default
            nr_requests=256
            ;;
        *)
            nr_requests=256
            ;;
    esac
    
    ultra_log_info "Block device queue configuration:"
    ultra_log_info "  nr_requests: $nr_requests (default: 128-256)"
    ultra_log_info "  Higher = better throughput, more latency"
    ultra_log_info "  Lower = better latency, less throughput"
    
    # Get block devices
    local devices=$(lsblk -d -n -o NAME 2>/dev/null | grep -v "loop\|ram")
    ultra_log_info ""
    ultra_log_info "Block devices: $devices"
    
    if ultra_is_dry_run; then
        ultra_log_info "[DRY-RUN] Would set nr_requests=$nr_requests"
        ultra_state_finalize_module "$MOD_ID" "success"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    # Create udev rule for persistent configuration
    local udev_rule="/etc/udev/rules.d/60-ultra-io-nr-requests.rules"
    
    [[ -f "$udev_rule" ]] && ultra_backup_file "$udev_rule" "$MOD_ID"
    
    cat > "$udev_rule" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# Set block device queue depth

# Apply to all block devices (exclude loop/ram)
ACTION=="add|change", KERNEL=="sd*|nvme*|vd*|xvd*", ATTR{queue/nr_requests}="$nr_requests"
EOF
    
    ultra_log_info "✅ Created udev rule: $udev_rule"
    
    # Apply immediately to existing devices
    for dev in $devices; do
        if [[ -f /sys/block/$dev/queue/nr_requests ]]; then
            local old_value=$(cat /sys/block/$dev/queue/nr_requests)
            echo "$nr_requests" > /sys/block/$dev/queue/nr_requests 2>/dev/null || true
            local new_value=$(cat /sys/block/$dev/queue/nr_requests)
            
            ultra_log_info "  /dev/$dev: $old_value -> $new_value"
        fi
    done
    
    # Reload udev rules
    udevadm control --reload-rules &>/dev/null
    udevadm trigger --subsystem-match=block &>/dev/null
    
    ultra_state_add_action "$MOD_ID" "io" "nr_requests=$nr_requests for: $devices"
    ultra_log_info "✅ Queue depth configured"
    
    ultra_log_info ""
    ultra_log_info "I/O queue monitoring:"
    ultra_log_info "  cat /sys/block/<dev>/queue/nr_requests"
    ultra_log_info "  iostat -x 1                    # Monitor I/O stats"
    ultra_log_info "  cat /proc/diskstats            # Detailed disk stats"
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    local udev_rule="/etc/udev/rules.d/60-ultra-io-nr-requests.rules"
    
    if [[ -f "$udev_rule" ]]; then
        rm -f "$udev_rule"
        ultra_log_info "Removed udev rule: $udev_rule"
        
        udevadm control --reload-rules &>/dev/null
        udevadm trigger --subsystem-match=block &>/dev/null
    fi
    
    # Reset to default (256)
    local devices=$(lsblk -d -n -o NAME 2>/dev/null | grep -v "loop\|ram")
    for dev in $devices; do
        if [[ -f /sys/block/$dev/queue/nr_requests ]]; then
            echo "256" > /sys/block/$dev/queue/nr_requests 2>/dev/null || true
        fi
    done
    
    ultra_log_info "Rollback complete"
}

mod_verify() {
    ultra_log_info "Block Device Queue Configuration:"
    
    if [[ -f /etc/udev/rules.d/60-ultra-io-nr-requests.rules ]]; then
        ultra_log_info "✅ Udev rule exists"
        grep "nr_requests" /etc/udev/rules.d/60-ultra-io-nr-requests.rules
    else
        ultra_log_warn "❌ Udev rule not found"
    fi
    
    ultra_log_info ""
    ultra_log_info "Current queue depth per device:"
    
    local devices=$(lsblk -d -n -o NAME 2>/dev/null | grep -v "loop\|ram")
    for dev in $devices; do
        if [[ -f /sys/block/$dev/queue/nr_requests ]]; then
            local nr=$(cat /sys/block/$dev/queue/nr_requests)
            local type=$(cat /sys/block/$dev/queue/rotational 2>/dev/null)
            local type_str="SSD"
            [[ "$type" == "1" ]] && type_str="HDD"
            
            ultra_log_info "  /dev/$dev ($type_str): nr_requests=$nr"
        fi
    done
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
