#!/bin/bash
# modules/kernel/io/io-write-cache.sh
# Module: Write cache policy configuration
# Controls disk write cache for reliability vs performance

MOD_ID="kernel.io.write-cache"
MOD_DESC="Write cache policy"
MOD_STAGE="kernel-io"
MOD_RISK="medium"
MOD_DEFAULT_ENABLED="false"

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    # Check if hdparm is available
    if ! command -v hdparm &>/dev/null; then
        ultra_log_debug "hdparm not available"
        return 1
    fi
    
    # Check if we have block devices
    local devices=$(lsblk -d -n -o NAME 2>/dev/null | grep -v "loop\|ram\|nvme")
    if [[ -z "$devices" ]]; then
        ultra_log_debug "No compatible block devices found"
        return 1
    fi
    
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying write cache policy optimization..."
    
    local profile=$(ultra_get_profile)
    
    # Write cache modes:
    # Enabled (-W1): Better performance, risk of data loss on power failure
    # Disabled (-W0): Safer, slower writes
    # 
    # Modern SSDs/NVMe have power-loss protection (PLP/supercap)
    # HDDs without BBU should disable write cache for databases
    
    local enable_write_cache="auto"
    
    case "$profile" in
        server)
            # Auto: check for BBU/PLP
            enable_write_cache="auto"
            ;;
        db)
            # Databases: safety first
            enable_write_cache="no"
            ;;
        lowlatency)
            # Performance first
            enable_write_cache="yes"
            ;;
        desktop)
            # Desktop: enable for speed
            enable_write_cache="yes"
            ;;
        *)
            enable_write_cache="auto"
            ;;
    esac
    
    ultra_log_info "Write cache policy:"
    ultra_log_info "  Profile: $profile"
    ultra_log_info "  Policy: $enable_write_cache"
    ultra_log_info ""
    ultra_log_info "  yes = Enabled (better performance, data loss risk)"
    ultra_log_info "  no  = Disabled (safer, slower writes)"
    ultra_log_info "  auto = Enable for SSD/NVMe, disable for HDD"
    
    # Get block devices (exclude NVMe, they handle this differently)
    local devices=$(lsblk -d -n -o NAME 2>/dev/null | grep "^sd" | grep -v "loop\|ram")
    
    if [[ -z "$devices" ]]; then
        ultra_log_warn "No SATA/SAS devices found (NVMe uses different mechanism)"
        ultra_state_finalize_module "$MOD_ID" "skipped"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    ultra_log_info ""
    ultra_log_info "SATA/SAS devices: $devices"
    
    if ultra_is_dry_run; then
        ultra_log_info "[DRY-RUN] Would configure write cache"
        ultra_state_finalize_module "$MOD_ID" "success"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    # Install hdparm if needed
    if ! command -v hdparm &>/dev/null; then
        ultra_log_info "Installing hdparm..."
        apt-get install -y hdparm &>/dev/null
    fi
    
    # Create systemd service
    local service_dir="/etc/systemd/system"
    local service_file="$service_dir/ultra-io-write-cache.service"
    local script_file="/usr/local/bin/ultra-io-write-cache.sh"
    
    [[ -f "$service_file" ]] && ultra_backup_file "$service_file" "$MOD_ID"
    [[ -f "$script_file" ]] && ultra_backup_file "$script_file" "$MOD_ID"
    
    # Create script
    cat > "$script_file" <<EOF
#!/bin/bash
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# Configure write cache policy

POLICY="$enable_write_cache"

configure_device() {
    local dev="\$1"
    
    if [[ ! -b "/dev/\$dev" ]]; then
        return 1
    fi
    
    # Check if device is rotational (HDD=1, SSD=0)
    local is_rotational=0
    if [[ -f /sys/block/\$dev/queue/rotational ]]; then
        is_rotational=\$(cat /sys/block/\$dev/queue/rotational)
    fi
    
    local enable_cache=1
    
    case "\$POLICY" in
        yes)
            enable_cache=1
            ;;
        no)
            enable_cache=0
            ;;
        auto)
            # Auto: enable for SSD, disable for HDD
            if [[ \$is_rotational -eq 1 ]]; then
                enable_cache=0  # HDD: disable for safety
            else
                enable_cache=1  # SSD: enable for performance
            fi
            ;;
    esac
    
    # Apply setting
    if [[ \$enable_cache -eq 1 ]]; then
        hdparm -W1 /dev/\$dev &>/dev/null
        echo "  /dev/\$dev: Write cache ENABLED"
    else
        hdparm -W0 /dev/\$dev &>/dev/null
        echo "  /dev/\$dev: Write cache DISABLED"
    fi
}

echo "Configuring write cache policy: \$POLICY"

DEVICES="$devices"
for dev in \$DEVICES; do
    configure_device "\$dev"
done
EOF
    
    chmod +x "$script_file"
    ultra_log_info "✅ Created: $script_file"
    
    # Create systemd service
    cat > "$service_file" <<EOF
[Unit]
Description=Ubuntu Ultra Optimizer - Write Cache Policy
After=local-fs.target

[Service]
Type=oneshot
ExecStart=$script_file
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
    
    ultra_log_info "✅ Created: $service_file"
    
    # Enable and start service
    systemctl daemon-reload
    systemctl enable ultra-io-write-cache.service &>/dev/null
    systemctl start ultra-io-write-cache.service &>/dev/null
    
    ultra_state_add_action "$MOD_ID" "io" "Write cache policy: $enable_write_cache"
    ultra_log_info "✅ Write cache configured"
    
    ultra_log_info ""
    ultra_log_info "⚠️  Important notes:"
    ultra_log_info "  - Write cache enabled = RISK of data loss on power failure"
    ultra_log_info "  - Use UPS for systems with enabled write cache"
    ultra_log_info "  - Databases should use write cache DISABLED or BBU"
    ultra_log_info "  - Modern SSDs often have power-loss protection"
    
    ultra_log_info ""
    ultra_log_info "Check write cache status:"
    ultra_log_info "  hdparm -W /dev/sda"
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    # Stop and disable service
    systemctl stop ultra-io-write-cache.service &>/dev/null
    systemctl disable ultra-io-write-cache.service &>/dev/null
    
    # Remove files
    rm -f /etc/systemd/system/ultra-io-write-cache.service
    rm -f /usr/local/bin/ultra-io-write-cache.sh
    
    systemctl daemon-reload
    
    ultra_log_info "Rollback complete"
    ultra_log_info "Note: Write cache policy reset to device defaults"
}

mod_verify() {
    ultra_log_info "Write Cache Configuration:"
    
    if [[ -f /etc/systemd/system/ultra-io-write-cache.service ]]; then
        ultra_log_info "✅ Service exists"
        
        if systemctl is-active ultra-io-write-cache.service &>/dev/null; then
            ultra_log_info "✅ Service is active"
        else
            ultra_log_warn "❌ Service is not active"
        fi
    else
        ultra_log_warn "❌ Service not found"
    fi
    
    ultra_log_info ""
    ultra_log_info "Current write cache status:"
    
    if command -v hdparm &>/dev/null; then
        local devices=$(lsblk -d -n -o NAME 2>/dev/null | grep "^sd")
        for dev in $devices; do
            if [[ -b "/dev/$dev" ]]; then
                local status=$(hdparm -W /dev/$dev 2>/dev/null | grep "write-caching" || echo "unknown")
                local rotational=$(cat /sys/block/$dev/queue/rotational 2>/dev/null || echo "?")
                local type="SSD"
                [[ "$rotational" == "1" ]] && type="HDD"
                
                ultra_log_info "  /dev/$dev ($type): $status"
            fi
        done
    else
        ultra_log_warn "hdparm not available"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
