#!/bin/bash
# modules/kernel/sched/sched-cpu-isolation.sh
# Module: CPU isolation for dedicated workloads
# Isolates CPUs from kernel scheduler for latency-sensitive tasks

MOD_ID="kernel.sched.cpu-isolation"
MOD_DESC="CPU isolation (isolcpus, nohz_full)"
MOD_STAGE="kernel-sched"
MOD_RISK="high"
MOD_DEFAULT_ENABLED="false"  # Requires GRUB changes and reboot

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    local profile=$(ultra_get_profile)
    
    # Only for low-latency profile by default
    if [[ "$profile" != "lowlatency" ]]; then
        ultra_log_debug "CPU isolation only recommended for lowlatency profile"
        return 1
    fi
    
    # Need at least 4 cores (isolate some, leave others for system)
    local cores=$(ultra_hw_cpu_get_cores_logical 2>/dev/null || echo "2")
    if [[ "$cores" -lt 4 ]]; then
        ultra_log_warn "CPU isolation requires at least 4 cores (found: $cores)"
        return 1
    fi
    
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying CPU isolation optimization..."
    
    local cores=$(ultra_hw_cpu_get_cores_logical)
    local cores_phys=$(ultra_hw_cpu_get_cores_physical 2>/dev/null || echo "$cores")
    
    # Strategy: Isolate cores 2 to N-1, keep 0-1 for system
    # This assumes NUMA node 0, adjust for multi-socket
    local isolate_start=2
    local isolate_end=$((cores - 1))
    
    if [[ "$cores" -le 4 ]]; then
        # 4 cores: isolate 2-3
        isolate_start=2
        isolate_end=3
    elif [[ "$cores" -le 8 ]]; then
        # 8 cores: isolate 2-7
        isolate_start=2
        isolate_end=7
    else
        # Many cores: leave 2 for system, isolate rest
        isolate_start=2
        isolate_end=$((cores - 1))
    fi
    
    local isolcpus_range="${isolate_start}-${isolate_end}"
    
    ultra_log_info "System has $cores logical cores ($cores_phys physical)"
    ultra_log_info "Will isolate CPUs: $isolcpus_range"
    ultra_log_info "System CPUs: 0-1 (for kernel, interrupts, system tasks)"
    ultra_log_info "Isolated CPUs: $isolcpus_range (for dedicated workloads)"
    
    # GRUB parameters needed:
    # isolcpus=<range> - Remove CPUs from general scheduler
    # nohz_full=<range> - Disable tick on isolated CPUs when running single task
    # rcu_nocbs=<range> - Offload RCU callbacks from isolated CPUs
    
    local grub_params="isolcpus=${isolcpus_range} nohz_full=${isolcpus_range} rcu_nocbs=${isolcpus_range}"
    
    ultra_log_warn "⚠️  CPU isolation requires GRUB changes and REBOOT"
    ultra_log_info "GRUB parameters to add: $grub_params"
    
    if ! ultra_is_dry_run; then
        # Add to GRUB
        ultra_edit_grub_add_param "isolcpus=${isolcpus_range}" "$MOD_ID"
        ultra_edit_grub_add_param "nohz_full=${isolcpus_range}" "$MOD_ID"
        ultra_edit_grub_add_param "rcu_nocbs=${isolcpus_range}" "$MOD_ID"
        
        ultra_state_add_action "$MOD_ID" "grub" "Added isolcpus=${isolcpus_range}"
        ultra_state_add_action "$MOD_ID" "grub" "Added nohz_full=${isolcpus_range}"
        ultra_state_add_action "$MOD_ID" "grub" "Added rcu_nocbs=${isolcpus_range}"
        
        ultra_log_info "✅ GRUB updated. Run 'update-grub' and REBOOT to apply."
        ultra_log_info ""
        ultra_log_info "After reboot, pin your latency-sensitive process to isolated CPUs:"
        ultra_log_info "  taskset -c ${isolcpus_range} your-application"
        ultra_log_info "  or: numactl --physcpubind=${isolcpus_range} your-application"
        ultra_log_info ""
        ultra_log_info "Verify isolation: cat /sys/devices/system/cpu/isolated"
    else
        ultra_log_info "[DRY-RUN] Would add to GRUB: $grub_params"
    fi
    
    # Also set CPU affinity for system services to CPUs 0-1
    if ! ultra_is_dry_run && command -v systemctl &>/dev/null; then
        ultra_log_info "Setting CPU affinity for systemd services..."
        
        # Create systemd config to restrict services to CPUs 0-1
        local systemd_conf="/etc/systemd/system.conf.d/99-ultra-opt-cpu-affinity.conf"
        mkdir -p "$(dirname "$systemd_conf")"
        
        cat > "$systemd_conf" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# Restrict system services to CPUs 0-1, leaving ${isolcpus_range} isolated

[Manager]
CPUAffinity=0-1
EOF
        
        ultra_state_add_action "$MOD_ID" "systemd" "Created $systemd_conf"
        ultra_log_info "Created: $systemd_conf"
        ultra_log_info "Run 'systemctl daemon-reload' after reboot"
    fi
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    local state_file="$ULTRA_STATE_DIR/$run_id/${MOD_ID}.json"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    ultra_log_warn "This requires manual GRUB editing and reboot"
    
    ultra_log_info "Remove these kernel parameters from /etc/default/grub:"
    ultra_log_info "  - isolcpus=..."
    ultra_log_info "  - nohz_full=..."
    ultra_log_info "  - rcu_nocbs=..."
    ultra_log_info "Then run: update-grub && reboot"
    
    # Remove systemd affinity config
    local systemd_conf="/etc/systemd/system.conf.d/99-ultra-opt-cpu-affinity.conf"
    if [[ -f "$systemd_conf" ]]; then
        rm -f "$systemd_conf"
        ultra_log_info "Removed: $systemd_conf"
    fi
}

mod_verify() {
    ultra_log_info "CPU Isolation Status:"
    
    # Check current kernel cmdline
    local cmdline=$(cat /proc/cmdline 2>/dev/null || echo "")
    
    if echo "$cmdline" | grep -q "isolcpus="; then
        local isolcpus=$(echo "$cmdline" | grep -oP 'isolcpus=\K[^ ]+')
        ultra_log_info "✅ isolcpus active: $isolcpus"
    else
        ultra_log_warn "❌ isolcpus not found in kernel cmdline"
    fi
    
    if echo "$cmdline" | grep -q "nohz_full="; then
        local nohz=$(echo "$cmdline" | grep -oP 'nohz_full=\K[^ ]+')
        ultra_log_info "✅ nohz_full active: $nohz"
    else
        ultra_log_warn "❌ nohz_full not found in kernel cmdline"
    fi
    
    # Show isolated CPUs
    if [[ -f /sys/devices/system/cpu/isolated ]]; then
        local isolated=$(cat /sys/devices/system/cpu/isolated)
        ultra_log_info "Isolated CPUs: $isolated"
    fi
    
    # Show systemd CPU affinity
    if [[ -f /etc/systemd/system.conf.d/99-ultra-opt-cpu-affinity.conf ]]; then
        ultra_log_info "✅ Systemd CPU affinity configured"
    fi
}

# Allow running standalone
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    echo "Usage: ./orchestrator/cli.sh --module $MOD_ID"
    exit 1
fi
