#!/bin/bash
# modules/services/svc-systemd-boot-fast.sh
# Module: Systemd timeout tuning for faster boot
# Reduces systemd timeouts to speed up boot and shutdown

MOD_ID="services.systemd-boot-fast"
MOD_DESC="Systemd timeout tuning"
MOD_STAGE="services"
MOD_RISK="low"
MOD_DEFAULT_ENABLED="true"

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    # Check if systemd is the init system
    if [[ ! -d /run/systemd/system ]]; then
        ultra_log_debug "systemd not detected"
        return 1
    fi
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying systemd timeout optimization..."
    
    local profile=$(ultra_get_profile)
    local config_dir="/etc/systemd/system.conf.d"
    local config_file="$config_dir/99-ultra-opt-timeouts.conf"
    
    # Systemd timeout configuration
    # Default timeouts are often too long (90s)
    # We'll reduce them for faster boot/shutdown
    
    local start_timeout=30
    local stop_timeout=30
    local device_timeout=30
    
    case "$profile" in
        server|lowlatency)
            # Servers need fast boot
            start_timeout=20
            stop_timeout=20
            device_timeout=20
            ;;
        db)
            # Databases may need more time
            start_timeout=45
            stop_timeout=45
            device_timeout=30
            ;;
        desktop)
            # Moderate timeouts for desktop
            start_timeout=30
            stop_timeout=30
            device_timeout=30
            ;;
        *)
            start_timeout=30
            stop_timeout=30
            device_timeout=30
            ;;
    esac
    
    ultra_log_info "Systemd timeout configuration:"
    ultra_log_info "  DefaultTimeoutStartSec: ${start_timeout}s (default: 90s)"
    ultra_log_info "  DefaultTimeoutStopSec: ${stop_timeout}s (default: 90s)"
    ultra_log_info "  DefaultDeviceTimeoutSec: ${device_timeout}s (default: 90s)"
    
    if ultra_is_dry_run; then
        ultra_log_info "[DRY-RUN] Would configure systemd timeouts"
        ultra_state_finalize_module "$MOD_ID" "success"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    # Create config directory
    mkdir -p "$config_dir"
    
    # Backup existing config
    [[ -f "$config_file" ]] && ultra_backup_file "$config_file" "$MOD_ID"
    
    # Create systemd config
    cat > "$config_file" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# Systemd timeout tuning for faster boot/shutdown

[Manager]
# Timeout for starting units (default: 90s)
DefaultTimeoutStartSec=${start_timeout}s

# Timeout for stopping units (default: 90s)
DefaultTimeoutStopSec=${stop_timeout}s

# Timeout for device units (default: 90s)
DefaultDeviceTimeoutSec=${device_timeout}s

# Restart units that fail to start (optional)
# DefaultRestartSec=100ms

# Show detailed boot status
#ShowStatus=yes

# Disable kernel log dumping to console (cleaner boot)
LogLevel=warning
EOF
    
    ultra_state_add_action "$MOD_ID" "systemd" "Created $config_file"
    ultra_log_info "✅ Created: $config_file"
    
    # Reload systemd configuration
    systemctl daemon-reload &>/dev/null
    ultra_log_info "✅ Systemd configuration reloaded"
    
    ultra_log_info ""
    ultra_log_info "Additional boot optimization tips:"
    ultra_log_info "  1. Disable unnecessary services:"
    ultra_log_info "     systemctl disable <service>"
    ultra_log_info "  2. Check boot time:"
    ultra_log_info "     systemd-analyze"
    ultra_log_info "  3. Find slow services:"
    ultra_log_info "     systemd-analyze blame"
    ultra_log_info "  4. View boot critical chain:"
    ultra_log_info "     systemd-analyze critical-chain"
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    local config_file="/etc/systemd/system.conf.d/99-ultra-opt-timeouts.conf"
    
    if [[ -f "$config_file" ]]; then
        rm -f "$config_file"
        ultra_log_info "Removed: $config_file"
        
        # Reload systemd
        systemctl daemon-reload &>/dev/null
        ultra_log_info "Systemd configuration reloaded"
    fi
}

mod_verify() {
    ultra_log_info "Systemd Configuration:"
    
    if [[ -f /etc/systemd/system.conf.d/99-ultra-opt-timeouts.conf ]]; then
        ultra_log_info "✅ Timeout config exists"
        grep "DefaultTimeout" /etc/systemd/system.conf.d/99-ultra-opt-timeouts.conf
    else
        ultra_log_warn "❌ Timeout config not found"
    fi
    
    ultra_log_info ""
    ultra_log_info "Boot time analysis:"
    if command -v systemd-analyze &>/dev/null; then
        systemd-analyze 2>/dev/null | head -3
        
        ultra_log_info ""
        ultra_log_info "Top 5 slowest services:"
        systemd-analyze blame 2>/dev/null | head -5
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
