#!/bin/bash
# modules/services/svc-journald-tune.sh
# Module: Journald size limits
# Controls systemd journal size to save disk space

MOD_ID="services.journald-tune"
MOD_DESC="Journald size limits"
MOD_STAGE="services"
MOD_RISK="low"
MOD_DEFAULT_ENABLED="true"

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    # Check if systemd-journald is running
    if ! systemctl is-active systemd-journald &>/dev/null; then
        ultra_log_debug "systemd-journald not active"
        return 1
    fi
    return 0
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying journald size optimization..."
    
    local profile=$(ultra_get_profile)
    local config_dir="/etc/systemd/journald.conf.d"
    local config_file="$config_dir/99-ultra-opt.conf"
    
    # Journald size configuration
    # Default: SystemMaxUse=10% of filesystem or 4G (whichever is smaller)
    # We'll set reasonable limits to prevent filling disk
    
    local max_use="500M"
    local max_file_size="50M"
    local max_retention="1week"
    local rate_limit_interval="30s"
    local rate_limit_burst="10000"
    
    case "$profile" in
        server)
            # Servers need more logs
            max_use="1G"
            max_file_size="100M"
            max_retention="2week"
            ;;
        db)
            # Databases generate lots of logs
            max_use="2G"
            max_file_size="200M"
            max_retention="2week"
            ;;
        lowlatency)
            # Minimal logging for low-latency
            max_use="250M"
            max_file_size="25M"
            max_retention="3days"
            rate_limit_interval="10s"
            rate_limit_burst="5000"
            ;;
        desktop)
            # Desktop needs less logging
            max_use="500M"
            max_file_size="50M"
            max_retention="1week"
            ;;
        *)
            max_use="500M"
            max_file_size="50M"
            max_retention="1week"
            ;;
    esac
    
    ultra_log_info "Journald configuration:"
    ultra_log_info "  SystemMaxUse: $max_use (total journal size)"
    ultra_log_info "  SystemMaxFileSize: $max_file_size (per file)"
    ultra_log_info "  MaxRetentionSec: $max_retention"
    ultra_log_info "  RateLimitInterval: $rate_limit_interval"
    ultra_log_info "  RateLimitBurst: $rate_limit_burst messages"
    
    if ultra_is_dry_run; then
        ultra_log_info "[DRY-RUN] Would configure journald"
        ultra_state_finalize_module "$MOD_ID" "success"
        ultra_log_module_end "$MOD_ID"
        return 0
    fi
    
    # Create config directory
    mkdir -p "$config_dir"
    
    # Backup existing config
    [[ -f "$config_file" ]] && ultra_backup_file "$config_file" "$MOD_ID"
    
    # Create journald config
    cat > "$config_file" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# Journald size and retention tuning

[Journal]
# Maximum disk space for all journal files
SystemMaxUse=$max_use

# Maximum size for individual journal files
SystemMaxFileSize=$max_file_size

# Keep journals for this long (time-based rotation)
MaxRetentionSec=$max_retention

# Forward to syslog (disable if not needed)
ForwardToSyslog=no

# Compress journal files
Compress=yes

# Rate limiting to prevent log flooding
RateLimitInterval=$rate_limit_interval
RateLimitBurst=$rate_limit_burst

# Storage location (persistent survives reboots)
Storage=persistent

# Sync interval (writes to disk)
SyncIntervalSec=5m
EOF
    
    ultra_state_add_action "$MOD_ID" "journald" "Created $config_file"
    ultra_log_info "✅ Created: $config_file"
    
    # Restart journald to apply changes
    systemctl restart systemd-journald &>/dev/null
    ultra_log_info "✅ Journald restarted"
    
    # Clean up old logs
    ultra_log_info ""
    ultra_log_info "Cleaning up old journal files..."
    journalctl --vacuum-size=$max_use &>/dev/null
    journalctl --vacuum-time=$max_retention &>/dev/null
    
    local current_size=$(journalctl --disk-usage 2>/dev/null | grep -oP 'Archived.*?:\s*\K[\d.]+[A-Z]')
    ultra_log_info "Current journal size: ${current_size:-unknown}"
    
    ultra_log_info ""
    ultra_log_info "Journal management commands:"
    ultra_log_info "  journalctl --disk-usage           # Check disk usage"
    ultra_log_info "  journalctl --vacuum-size=500M     # Limit to 500M"
    ultra_log_info "  journalctl --vacuum-time=1week    # Keep 1 week"
    ultra_log_info "  journalctl --rotate               # Rotate journals"
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    local config_file="/etc/systemd/journald.conf.d/99-ultra-opt.conf"
    
    if [[ -f "$config_file" ]]; then
        rm -f "$config_file"
        ultra_log_info "Removed: $config_file"
        
        # Restart journald
        systemctl restart systemd-journald &>/dev/null
        ultra_log_info "Journald restarted with default config"
    fi
}

mod_verify() {
    ultra_log_info "Journald Configuration:"
    
    if [[ -f /etc/systemd/journald.conf.d/99-ultra-opt.conf ]]; then
        ultra_log_info "✅ Journald config exists"
        grep -E "SystemMaxUse|SystemMaxFileSize" /etc/systemd/journald.conf.d/99-ultra-opt.conf
    else
        ultra_log_warn "❌ Journald config not found"
    fi
    
    ultra_log_info ""
    ultra_log_info "Current journal usage:"
    if command -v journalctl &>/dev/null; then
        journalctl --disk-usage 2>/dev/null
        
        ultra_log_info ""
        ultra_log_info "Journal files:"
        ls -lh /var/log/journal/*/*.journal 2>/dev/null | head -5
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
