#!/bin/bash
# modules/services/svc-limits-ulimit.sh  
# Module: User limits configuration (nofile, nproc, stack)
# Increases system limits for high-performance applications

MOD_ID="services.limits-ulimit"
MOD_DESC="User limits (ulimit) configuration"
MOD_STAGE="services"
MOD_RISK="low"
MOD_DEFAULT_ENABLED="true"

mod_id() {
    echo "$MOD_ID"
}

mod_can_run() {
    local profile=$(ultra_get_profile)
    
    # Useful for server and DB profiles
    if [[ "$profile" == "server" ]] || [[ "$profile" == "db" ]] || [[ "$profile" == "lowlatency" ]]; then
        return 0
    fi
    
    return 1
}

mod_apply() {
    ultra_log_module_start "$MOD_ID"
    ultra_log_info "Applying user limits optimization..."
    
    local profile=$(ultra_get_profile)
    local limits_conf="/etc/security/limits.d/99-ultra-opt.conf"
    local sysctl_conf="/etc/sysctl.d/99-ultra-opt-limits.conf"
    
    # Determine limits based on profile
    local nofile_soft=65536
    local nofile_hard=1048576
    local nproc_soft=32768
    local nproc_hard=65536
    local stack_soft=8192
    local stack_hard="unlimited"
    
    case "$profile" in
        server)
            nofile_soft=65536
            nofile_hard=1048576
            nproc_soft=32768
            nproc_hard=65536
            ;;
        db)
            # Databases need lots of file descriptors
            nofile_soft=1048576
            nofile_hard=1048576
            nproc_soft=65536
            nproc_hard=65536
            ;;
        lowlatency)
            nofile_soft=524288
            nofile_hard=1048576
            nproc_soft=65536
            nproc_hard=65536
            ;;
        *)
            nofile_soft=65536
            nofile_hard=524288
            ;;
    esac
    
    ultra_log_info "User limits configuration (profile: $profile):"
    ultra_log_info "  nofile (open files): soft=$nofile_soft, hard=$nofile_hard"
    ultra_log_info "  nproc (processes): soft=$nproc_soft, hard=$nproc_hard"
    ultra_log_info "  stack: soft=${stack_soft}KB, hard=$stack_hard"
    
    if ! ultra_is_dry_run; then
        # Backup existing config
        [[ -f "$limits_conf" ]] && ultra_backup_file "$limits_conf" "$MOD_ID"
        
        # Create limits config
        cat > "$limits_conf" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# User limits for high-performance applications

# Open files (nofile)
*    soft    nofile    $nofile_soft
*    hard    nofile    $nofile_hard
root soft    nofile    $nofile_hard
root hard    nofile    $nofile_hard

# Number of processes (nproc)
*    soft    nproc     $nproc_soft
*    hard    nproc     $nproc_hard
root soft    nproc     $nproc_hard
root hard    nproc     $nproc_hard

# Stack size
*    soft    stack     $stack_soft
*    hard    stack     $stack_hard

# Core dumps (disabled for security, enable if needed)
*    soft    core      0
*    hard    core      0

# Max locked memory (for databases with huge pages)
*    soft    memlock   unlimited
*    hard    memlock   unlimited
EOF
        
        ultra_state_add_action "$MOD_ID" "limits" "Created $limits_conf"
        ultra_log_info "✅ Created: $limits_conf"
        
        # Also set kernel limits
        cat > "$sysctl_conf" <<EOF
# Generated by Ubuntu Ultra Optimizer - $MOD_ID
# Kernel-level file descriptor limits

# System-wide file descriptor limit
fs.file-max = $((nofile_hard * 2))

# Per-user file descriptor limit
fs.nr_open = $nofile_hard

# Inotify watches (for file monitoring tools)
fs.inotify.max_user_watches = 524288
fs.inotify.max_user_instances = 512
EOF
        
        # Apply sysctl
        sysctl -p "$sysctl_conf" &>/dev/null
        
        ultra_state_add_action "$MOD_ID" "sysctl" "Created $sysctl_conf"
        ultra_log_info "✅ Created: $sysctl_conf"
        ultra_log_info ""
        ultra_log_info "Changes will take effect for NEW sessions"
        ultra_log_info "Current session limits unchanged - relogin or reboot"
    else
        ultra_log_info "[DRY-RUN] Would create $limits_conf and $sysctl_conf"
    fi
    
    ultra_state_finalize_module "$MOD_ID" "success"
    ultra_log_module_end "$MOD_ID"
}

mod_rollback() {
    local run_id="$1"
    
    ultra_log_info "Rolling back $MOD_DESC..."
    
    local limits_conf="/etc/security/limits.d/99-ultra-opt.conf"
    local sysctl_conf="/etc/sysctl.d/99-ultra-opt-limits.conf"
    
    if [[ -f "$limits_conf" ]]; then
        rm -f "$limits_conf"
        ultra_log_info "Removed: $limits_conf"
    fi
    
    if [[ -f "$sysctl_conf" ]]; then
        rm -f "$sysctl_conf"
        ultra_log_info "Removed: $sysctl_conf"
        # Reset to defaults
        sysctl -w fs.file-max=9223372036854775807 &>/dev/null
    fi
}

mod_verify() {
    ultra_log_info "Current limits:"
    ultra_log_info "  System file-max: $(cat /proc/sys/fs/file-max)"
    ultra_log_info "  System nr_open: $(cat /proc/sys/fs/nr_open)"
    
    if [[ -f /etc/security/limits.d/99-ultra-opt.conf ]]; then
        ultra_log_info "✅ Limits config exists"
        grep "nofile" /etc/security/limits.d/99-ultra-opt.conf | head -2
    fi
    
    ultra_log_info "Current session limits:"
    ultra_log_info "  Open files (nofile): $(ulimit -n)"
    ultra_log_info "  Processes (nproc): $(ulimit -u)"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "This module should be run through the orchestrator"
    exit 1
fi
